#!/usr/bin/env bash

set -euo pipefail

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

git clone https://github.com/zplug/zplug ~/.zplug

cp .zshrc ~/.zshrc
cp .vimrc ~/.vimrc
cp .gitconfig ~/.gitconfig
cp .gitignore ~/.gitignore

mkdir -p ~/.gnupg
cp gpg.conf ~/.gnupg
cp gpg-agent.conf ~/.gnupg

brew bundle

keybase pgp export | gpg --import
keybase pgp export --secret | gpg --import --allow-secret-key-import

chsh -s $(which zsh)
